channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==2.1.1
  - pandas==2.2.3
  - torch==2.4.1
  - tqdm==4.66.5
name: mlflow-env
